# -*- coding: utf-8 -*-
"""7_CRUD_workflow_DAI009_Sep14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUpyxvMhFxFGH0FW-Cf_A6OwaClse56n

# Core CRUD Workflow

**Workflows covered:**
1. Setup & Engine Connection
2. Read `friends` & `books` tables (+ test after each)
3. Create a friend & loan using dynamically selected row data (+ test)
4. Update a friend using dynamic selection (+ test)
5. Delete a friend using dynamic selection (+ test)

## 0. Setup & Engine Connection
"""

import pandas as pd
from sqlalchemy import create_engine, text

# Running this cell REQUIRES a module named con_lib.py in this notebook's PARENT DIRECTORY
# ALTERNATELY, provide a connection string in a different way
#schema = "Your_Schema"
#host = "127.0.0.1"
##user = "root"
#password = "YOUR_PASSWORD"
##port = 3306

#connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

import sys
sys.path.append("..") # con_lib is the parent directory of this notebook
from con_lib import connection_string

engine = create_engine(connection_string)

pd.read_sql('friends', con=engine)

pd.read_sql('books', con=connection_string)

pd.read_sql('loans', con=connection_string)

"""## 1. Read Operations"""

def read_friends():
    return pd.read_sql('friends', con=engine)

read_friends()

def read_books(available_only=False):
    books = pd.read_sql("books", con=engine)


    if available_only == True:
        loans= pd.read_sql("loans", con=engine)
        books = pd.merge(books, loans, on='isbn', how='left').query('friend_id.isna()')[books.columns]

    return books

read_books(available_only=True)

read_books(available_only=True)

read_books()

books = pd.read_sql("books", con=engine)
loans= pd.read_sql("loans", con=engine)

available_books = pd.merge(books, loans, on='isbn', how='left').query('friend_id.isna()')

available_books

read_books()

def read_loans():
    return pd.read_sql("loans", con=engine)

read_loans()

"""## 2. Create friend/Loan

"""

engine = create_engine(connection_string)

update_query= """
 INSERT INTO friends(`name`, max_loans)
 VALUES("Marie", 3);
"""

with engine.connect() as connection:
    transaction = connection.begin()
    try:                                          # Python will attempt to run the code inside this block.
        connection.execute(text(update_query))    # sends your raw SQL string (safely wrapped in the text() fucntion) to the database to be executed.
        transaction.commit()                      # If the execution is successful, this line tells the database to save the changes permanently. The transaction is now commplete!
    except:                                       # If any error occurs in the try block, Python immediately jumps here
        transaction.rollback()                    # This is the panic button. It tells the database to instantly undo any temporary changes made since connection.begin().
        raise

def create_friend(name, max_loans=3, notes=None):
    engine = create_engine(connection_string)

    update_query= """
        INSERT INTO friends(`name`, max_loans)
        VALUES(:fname, :max_loans);
    """

    with engine.connect() as connection:
        transaction = connection.begin()
        try:                                          # Python will attempt to run the code inside this block.
            connection.execute(text(update_query), {"fname" : name, "max_loans": max_loans})    # sends your raw SQL string (safely wrapped in the text() fucntion) to the database to be executed.
            transaction.commit()                      # If the execution is successful, this line tells the database to save the changes permanently. The transaction is now commplete!
        except:                                       # If any error occurs in the try block, Python immediately jumps here
            transaction.rollback()                    # This is the panic button. It tells the database to instantly undo any temporary changes made since connection.begin().
            raise

create_friend("Olena", 5)



read_friends()

# Example adding things with query

update_query = """
            INSERT INTO FRIENDS (`name`, max_loans)
            VALUES ('Semira', 3);
"""

with engine.connect() as connection:
    transaction = connection.begin()
    try:
        connection.execute(text(update_query))
        transaction.commit()
    except:
        transaction.rollback()
        raise

read_friends()

# Create_friend function using query insinde python

def create_friend(name, max_loans=5, notes=None):

    engine = create_engine(connection_string)

    update_query = """
        INSERT INTO friends (`name`, max_loans, notes)
        VALUES (:name, :max_loans, :notes);
    """

    with engine.begin() as connection:
        connection.execute(
            text(update_query),
            {
                "name": name,
                "max_loans": max_loans,
                "notes": notes
            }
        )

read_friends()

### With pandas
'''
books, friends

friend_name, isbn, loan_date, next_contact, notes

'''

def create_loan(friend_name, isbn, loan_date=None, next_contact=None, notes=None):
    friends_df = read_friends()
    books_df = read_books()

    # Find the friend_id from friends table
    friend = friends_df[friends_df['name'] == friend_name].iloc[0]

    # book_id
    book = books_df[books_df['isbn'] == isbn].iloc[0]

    df = pd.DataFrame([[book['isbn'],
                        friend['friend_id']],
                        loan_date,
                        next_contact,
                        notes],
                      columns=['isbn',
                               'friend_id',
                                 'loan_date',
                                 'next_contact',
                                 'notes'])
    df.to_sql('loans',
              if_exists='append',
              con=engine,
              index=False
              )
    return f"{friend_name} borrowed '{book['title']}' and this added to loans table."

friends_df = read_friends()

friend_name = 'Davey'

matching_friends = friends_df[friends_df["name"] == friend_name]

matching_friends

friend = matching_friends.iloc[0]

friend['notes']

loans_df = read_loans()



current_loans = len(loans_df[loans_df["friend_id"] == friend["friend_id"]])

current_loans

#### With SQL

def create_loan(friend_name, isbn, loan_date=None, next_contact=None, notes=None):

    friends_df = read_friends()
    books_df = read_books(available_only=True)
    loans_df = read_loans()

    # 1. LOOKUP: friend
    matching_friends = friends_df[friends_df["name"] == friend_name]
    if len(matching_friends) == 0:
        return f"Error: No friend found with name '{friend_name}'."
    friend = matching_friends.iloc[0]

    # 2. LOOKUP: book
    matching_books = books_df[books_df["isbn"] == isbn]
    if len(matching_books) == 0:
        return f"Error: No book found with isbn '{isbn}'."
    book = matching_books.iloc[0]

    # 3. CHECK MAX LOANS: count current loans for this friend
    current_loans = len(loans_df[loans_df["friend_id"] == friend["friend_id"]])
    if current_loans >= friend["max_loans"]:
        return f"Warning: '{friend['name']}' has reached their maximum loan allowance ({friend['max_loans']})."

    # 4. DATES: default logic
    if loan_date is None:
        loan_date = pd.Timestamp.today().date()
    if next_contact is None:
        next_contact = loan_date + pd.Timedelta(30, "D")

    # 5. INSERT: create loan record using a SQL query
    engine = create_engine(connection_string)

    insert_query = """
        INSERT INTO loans (isbn, friend_id, loan_date, next_contact, notes)
        VALUES (:isbn, :friend_id, :loan_date, :next_contact, :notes);
    """

    with engine.begin() as connection:
        connection.execute(
            text(insert_query),
            {
                "isbn": book["isbn"],
                "friend_id": friend["friend_id"],
                "loan_date": loan_date,
                "next_contact": next_contact,
                "notes": notes
            }
        )

    return f"Added '{friend['name']}' borrowed '{book['title']}' to 'loans'."

read_books(available_only=True)

create_loan('Davey','9780143127741')

read_loans()

read_books(available_only=True)

read_loans()

create_loan("Semira", "9785566778899")

"""## 3. Update Friend"""

def update_friend(friend_name, field, new_data):

    friends_df = read_friends()

    matching_friends = friends_df[friends_df["name"] == friend_name]
    if len(matching_friends) == 0:
        return f"Warning: '{friend_name}' not found."

    friend_id = matching_friends.iloc[0]["friend_id"]

    engine = create_engine(connection_string)

    query = f"""
        UPDATE friends
        SET {field} = :val
        WHERE friend_id = :id;
    """

    with engine.begin() as connection:
        connection.execute(
            text(query),
            {"val": new_data, "id": friend_id}
        )

    return f"'{field}' has been updated for '{friend_name}'."

update_friend('Davey', 'notes', 'we dont like him anymore')

"""## 4. Delete Friend"""

read_friends()

def delete_friend(friend_name):

    friends_df = read_friends()

    matching_friends = friends_df[friends_df["name"] == friend_name]
    if len(matching_friends) == 0:
        return f"Warning: '{friend_name}' doesn't exist in friends list."

    friend_id = matching_friends.iloc[0]["friend_id"]

    engine = create_engine(connection_string)

    query = """
        DELETE FROM friends
        WHERE friend_id = :id;
    """

    with engine.begin() as connection:
        connection.execute(
            text(query),
            {"id": friend_id}
        )

    return f"'{friend_name}' has been deleted."

delete_friend("Semira")

read_friends()

delete_friend('Marie')

read_friends()